<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <Version>2026.1.4</Version>
    <AssemblyVersion>2026.1.4.0</AssemblyVersion>
    <FileVersion>2026.1.4.0</FileVersion>
    <InformationalVersion>2026.1.4</InformationalVersion>
    <Authors>Alexander Weschnin</Authors>
    <Product>BIMassist für Revit 2026</Product>
    <Description>BIMassist Add-In für Autodesk Revit 2026</Description>
    <Copyright>© Alexander Weschnin. Alle Rechte vorbehalten.</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App.WPF" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="AWESBox\**\*.cs" />
    <Page Remove="AWESBox\**\*.xaml" />
    <EmbeddedResource Remove="AWESBox\**\*" />
    <Resource Remove="AWESBox\**\*" />
    <None Remove="AWESBox\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>..\..\..\..\..\Program Files\Autodesk\Revit 2026\RevitAPI.dll</HintPath>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>..\..\..\..\..\Program Files\Autodesk\Revit 2026\RevitAPIUI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\3D Box.png" />
    <None Remove="Resources\addDoc_32px.png" />
    <None Remove="Resources\add_32px.png" />
    <None Remove="Resources\Aktualisieren 16.png" />
    <None Remove="Resources\Aktualisieren 24.png" />
    <None Remove="Resources\arrow_16px.png" />
    <None Remove="Resources\arrow_24px.png" />
    <None Remove="Resources\boolean_16px.png" />
    <None Remove="Resources\boolean_24px.png" />
    <None Remove="Resources\boolean_32px.png" />
    <None Remove="Resources\change_32px.png" />
    <None Remove="Resources\collapsed_32px.png" />
    <None Remove="Resources\copyright_16px.png" />
    <None Remove="Resources\copyright_20px.png" />
    <None Remove="Resources\copyright_24px.png" />
    <None Remove="Resources\copy_32.png" />
    <None Remove="Resources\cut_16px.png" />
    <None Remove="Resources\cut_24px.png" />
    <None Remove="Resources\cut_32px.png" />
    <None Remove="Resources\decke_16px.png" />
    <None Remove="Resources\decke_24px.png" />
    <None Remove="Resources\delal_32px.png" />
    <None Remove="Resources\delDoc_32px.png" />
    <None Remove="Resources\delFolder_32px.png" />
    <None Remove="Resources\del_16px.png" />
    <None Remove="Resources\del_24px.png" />
    <None Remove="Resources\del_32px.png" />
    <None Remove="Resources\doc_16px.png" />
    <None Remove="Resources\doc_24px.png" />
    <None Remove="Resources\doc_32px.png" />
    <None Remove="Resources\down_32.png" />
    <None Remove="Resources\Einstellungen 16.png" />
    <None Remove="Resources\Einstellungen 24.png" />
    <None Remove="Resources\Einstellungen_16px.png" />
    <None Remove="Resources\Einstellungen_24px.png" />
    <None Remove="Resources\Einstellungen_32px.ico" />
    <None Remove="Resources\Einstellungen_32px.png" />
    <None Remove="Resources\expand_32px.png" />
    <None Remove="Resources\expand_collapsed2_32px.png" />
    <None Remove="Resources\expand_collapsed_32px.png" />
    <None Remove="Resources\export_16px.png" />
    <None Remove="Resources\export_24px.png" />
    <None Remove="Resources\eye_off_16px.png" />
    <None Remove="Resources\eye_off_20px.png" />
    <None Remove="Resources\eye_off_32px.png" />
    <None Remove="Resources\floppy-disk.png" />
    <None Remove="Resources\Fortschritt_16px.png" />
    <None Remove="Resources\Fortschritt_24px.png" />
    <None Remove="Resources\IFC.png" />
    <None Remove="Resources\ifcexport_16px.png" />
    <None Remove="Resources\ifcexport_24px.png" />
    <None Remove="Resources\ifcexport_32px.png" />
    <None Remove="Resources\IFC_16px.png" />
    <None Remove="Resources\IFC_24px.png" />
    <None Remove="Resources\IFC_32px.png" />
    <None Remove="Resources\import_16px.png" />
    <None Remove="Resources\import_24px.png" />
    <None Remove="Resources\info_16px.png" />
    <None Remove="Resources\info_24px.png" />
    <None Remove="Resources\Label_16px.png" />
    <None Remove="Resources\label_24px.png" />
    <None Remove="Resources\left_32px.png" />
    <None Remove="Resources\LoadDocu_16px.png" />
    <None Remove="Resources\LoadDocu_24px.png" />
    <None Remove="Resources\material_16px.png" />
    <None Remove="Resources\material_32px.png" />
    <None Remove="Resources\metadata_32px.png" />
    <None Remove="Resources\one_32px.png" />
    <None Remove="Resources\openDoc_32px.png" />
    <None Remove="Resources\PDFDocu.ico" />
    <None Remove="Resources\PDFDocu_16px.png" />
    <None Remove="Resources\PDFDocu_24px.png" />
    <None Remove="Resources\PDFDocu_32px.png" />
    <None Remove="Resources\pipe_16px.png" />
    <None Remove="Resources\pipe_24px.png" />
    <None Remove="Resources\pipe_32px.png" />
    <None Remove="Resources\refresh_16px.png" />
    <None Remove="Resources\refresh_24px.png" />
    <None Remove="Resources\repeatone_32px.png" />
    <None Remove="Resources\repeat_32px.png" />
    <None Remove="Resources\right_32px.png" />
    <None Remove="Resources\SaveDocu_16px.png" />
    <None Remove="Resources\SaveDocu_24px.png" />
    <None Remove="Resources\Schloss_auf_32.png" />
    <None Remove="Resources\Schloss_zu_32.png" />
    <None Remove="Resources\settings_32px.png" />
    <None Remove="Resources\Share_24px.png" />
    <None Remove="Resources\Share_32px.png" />
    <None Remove="Resources\Share_48px.png" />
    <None Remove="Resources\Share_64px.png" />
    <None Remove="Resources\solid_16px.png" />
    <None Remove="Resources\solid_24px.png" />
    <None Remove="Resources\toggleOFF.png" />
    <None Remove="Resources\toggleON.png" />
    <None Remove="Resources\transferFam_16px.png" />
    <None Remove="Resources\transferFam_24px.png" />
    <None Remove="Resources\transfer_16px.png" />
    <None Remove="Resources\transfer_24px.png" />
    <None Remove="Resources\treestructure_32px.png" />
    <None Remove="Resources\update_16px.png" />
    <None Remove="Resources\update_24px.png" />
    <None Remove="Resources\update_32px.png" />
    <None Remove="Resources\up_32.png" />
    <None Remove="Resources\wall_16px.png" />
    <None Remove="Resources\wall_24px.png" />
    <None Remove="Resources\writeIntoFamily_16px.png" />
    <None Remove="Resources\writeIntoFamily_24px.png" />
    <None Remove="Resources\writeIntoFamily_32px.png" />
    <None Remove="Resources\Zuweisen_16px.png" />
    <None Remove="Resources\Zuweisen_24px.png" />
    <None Remove="Resources\Zuweisen_32px.ico" />
    <None Remove="Resources\Zuweisen_32px.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\3D Box.png" />
    <EmbeddedResource Include="Resources\addDoc_32px.png" />
    <EmbeddedResource Include="Resources\add_32px.png" />
    <EmbeddedResource Include="Resources\Aktualisieren 16.png" />
    <EmbeddedResource Include="Resources\Aktualisieren 24.png" />
    <EmbeddedResource Include="Resources\arrow_16px.png" />
    <EmbeddedResource Include="Resources\arrow_24px.png" />
    <EmbeddedResource Include="Resources\boolean_16px.png" />
    <EmbeddedResource Include="Resources\boolean_24px.png" />
    <EmbeddedResource Include="Resources\boolean_32px.png" />
    <EmbeddedResource Include="Resources\change_32px.png" />
    <EmbeddedResource Include="Resources\collapsed_32px.png" />
    <EmbeddedResource Include="Resources\copyright_16px.png" />
    <EmbeddedResource Include="Resources\copyright_20px.png" />
    <EmbeddedResource Include="Resources\copyright_24px.png" />
    <EmbeddedResource Include="Resources\copy_32.png" />
    <EmbeddedResource Include="Resources\cut_16px.png" />
    <EmbeddedResource Include="Resources\cut_24px.png" />
    <EmbeddedResource Include="Resources\cut_32px.png" />
    <EmbeddedResource Include="Resources\decke_16px.png" />
    <EmbeddedResource Include="Resources\decke_24px.png" />
    <EmbeddedResource Include="Resources\delal_32px.png" />
    <EmbeddedResource Include="Resources\delDoc_32px.png" />
    <EmbeddedResource Include="Resources\delFolder_32px.png" />
    <EmbeddedResource Include="Resources\del_16px.png" />
    <EmbeddedResource Include="Resources\del_24px.png" />
    <EmbeddedResource Include="Resources\del_32px.png" />
    <EmbeddedResource Include="Resources\doc_16px.png" />
    <EmbeddedResource Include="Resources\doc_24px.png" />
    <EmbeddedResource Include="Resources\doc_32px.png" />
    <EmbeddedResource Include="Resources\down_32.png" />
    <EmbeddedResource Include="Resources\Einstellungen 16.png" />
    <EmbeddedResource Include="Resources\Einstellungen 24.png" />
    <EmbeddedResource Include="Resources\Einstellungen_16px.png" />
    <EmbeddedResource Include="Resources\Einstellungen_24px.png" />
    <EmbeddedResource Include="Resources\Einstellungen_32px.ico" />
    <EmbeddedResource Include="Resources\Einstellungen_32px.png" />
    <EmbeddedResource Include="Resources\expand_32px.png" />
    <EmbeddedResource Include="Resources\expand_collapsed2_32px.png" />
    <EmbeddedResource Include="Resources\expand_collapsed_32px.png" />
    <EmbeddedResource Include="Resources\export_16px.png" />
    <EmbeddedResource Include="Resources\eye_off_16px.png" />
    <EmbeddedResource Include="Resources\eye_off_20px.png" />
    <EmbeddedResource Include="Resources\eye_off_32px.png" />
    <EmbeddedResource Include="Resources\floppy-disk.png" />
    <EmbeddedResource Include="Resources\Fortschritt_16px.png" />
    <EmbeddedResource Include="Resources\Fortschritt_24px.png" />
    <EmbeddedResource Include="Resources\geometrie_16px.png" />
    <EmbeddedResource Include="Resources\geometrie_32px.png" />
    <EmbeddedResource Include="Resources\IFC.png" />
    <EmbeddedResource Include="Resources\ifcexport_16px.png" />
    <EmbeddedResource Include="Resources\ifcexport_24px.png" />
    <EmbeddedResource Include="Resources\ifcexport_32px.png" />
    <EmbeddedResource Include="Resources\IFC_16px.png" />
    <EmbeddedResource Include="Resources\IFC_24px.png" />
    <EmbeddedResource Include="Resources\IFC_32px.png" />
    <EmbeddedResource Include="Resources\import_16px.png" />
    <EmbeddedResource Include="Resources\import_24px.png" />
    <EmbeddedResource Include="Resources\info_16px.png" />
    <EmbeddedResource Include="Resources\info_24px.png" />
    <EmbeddedResource Include="Resources\label_16px.png" />
    <EmbeddedResource Include="Resources\label_24px.png" />
    <EmbeddedResource Include="Resources\left_32px.png" />
    <EmbeddedResource Include="Resources\LoadDocu_16px.png" />
    <EmbeddedResource Include="Resources\LoadDocu_24px.png" />
    <EmbeddedResource Include="Resources\metadata_16px.png" />
    <EmbeddedResource Include="Resources\material_16px.png" />
    <EmbeddedResource Include="Resources\material_32px.png" />
    <EmbeddedResource Include="Resources\metadata_32px.png" />
    <EmbeddedResource Include="Resources\one_32px.png" />
    <EmbeddedResource Include="Resources\openDoc_32px.png" />
    <EmbeddedResource Include="Resources\PDFDocu.ico" />
    <EmbeddedResource Include="Resources\PDFDocu_16px.png" />
    <EmbeddedResource Include="Resources\PDFDocu_24px.png" />
    <EmbeddedResource Include="Resources\PDFDocu_32px.png" />
    <EmbeddedResource Include="Resources\pipe_16px.png" />
    <EmbeddedResource Include="Resources\pipe_24px.png" />
    <EmbeddedResource Include="Resources\pipe_32px.png" />
    <EmbeddedResource Include="Resources\refresh_16px.png" />
    <EmbeddedResource Include="Resources\refresh_24px.png" />
    <EmbeddedResource Include="Resources\repeatone_32px.png" />
    <EmbeddedResource Include="Resources\repeat_32px.png" />
    <EmbeddedResource Include="Resources\right_32px.png" />
    <EmbeddedResource Include="Resources\SaveDocu_16px.png" />
    <EmbeddedResource Include="Resources\SaveDocu_24px.png" />
    <EmbeddedResource Include="Resources\Schloss_auf_32.png" />
    <EmbeddedResource Include="Resources\Schloss_zu_32.png" />
    <EmbeddedResource Include="Resources\settings_32px.png" />
    <EmbeddedResource Include="Resources\Share_24px.png" />
    <EmbeddedResource Include="Resources\Share_32px.png" />
    <EmbeddedResource Include="Resources\Share_48px.png" />
    <EmbeddedResource Include="Resources\Share_64px.png" />
    <EmbeddedResource Include="Resources\solid_16px.png" />
    <EmbeddedResource Include="Resources\solid_24px.png" />
    <EmbeddedResource Include="Resources\toggleOFF.png" />
    <EmbeddedResource Include="Resources\toggleON.png" />
    <EmbeddedResource Include="Resources\transferFam_16px.png" />
    <EmbeddedResource Include="Resources\transferFam_24px.png" />
    <EmbeddedResource Include="Resources\transfer_16px.png" />
    <EmbeddedResource Include="Resources\treestructure_32px.png" />
    <EmbeddedResource Include="Resources\update_16px.png" />
    <EmbeddedResource Include="Resources\update_24px.png" />
    <EmbeddedResource Include="Resources\update_32px.png" />
    <EmbeddedResource Include="Resources\up_32.png" />
    <EmbeddedResource Include="Resources\wall_16px.png" />
    <EmbeddedResource Include="Resources\wall_24px.png" />
    <EmbeddedResource Include="Resources\writeIntoFamily_16px.png" />
    <EmbeddedResource Include="Resources\writeIntoFamily_24px.png" />
    <EmbeddedResource Include="Resources\writeIntoFamily_32px.png" />
    <EmbeddedResource Include="Resources\Zuweisen_16px.png" />
    <EmbeddedResource Include="Resources\Zuweisen_24px.png" />
    <EmbeddedResource Include="Resources\Zuweisen_32px.ico" />
    <EmbeddedResource Include="Resources\Zuweisen_32px.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\copilot-instructions.md" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <!-- Make images available as WPF Resource so pack://application URIs resolve in XAML -->
    <Resource Include="Resources\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /y /d &quot;$(TargetPath)&quot; &quot;C:\Users\wesch\AppData\Roaming\Autodesk\Revit\Addins\2026&quot;&#xA;xcopy /y /d &quot;$(ProjectDir)*.addin&quot; &quot;C:\Users\wesch\AppData\Roaming\Autodesk\Revit\Addins\2026&quot;&#xA;" />
  </Target>

</Project>
